import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,Settings,ChevronDown,ChevronUp,Play,Pause,AudioLines,MonitorPlay,Gauge,Volume2,X}from'lucide-react';
interface Props{animeTitle:string;episodeNumber:string|number;episodeTitle?:string;currentEpisodeIndex:number;episodes:any[];seasons:any[];currentSeason?:number;recommendations?:any[];isMovie?:boolean;isOpen:boolean;initialDrawer?:'episodes'|'settings'|'more'|null;onClose:()=>void;onBack:()=>void;onPlayEpisode:(id:string,timestamp?:number)=>void;selectedType:string;onSelectType:(v:string)=>void;servers:any[];selectedServer?:string;onSelectServer:(v:string)=>void;currentTime?:number;duration?:number;isPlaying?:boolean;onTogglePlay?:()=>void;onSeek?:(t:number)=>void;}
const fmt=(n:number)=>{if(!Number.isFinite(n)||n<0)return'00:00';const s=Math.floor(n),m=Math.floor(s/60),h=Math.floor(m/60);return h?String(h)+':'+String(m%60).padStart(2,'0')+':'+String(s%60).padStart(2,'0'):String(m).padStart(2,'0')+':'+String(s%60).padStart(2,'0')};
export function TVPlayerOSD(p:Props){
 const{isOpen,initialDrawer=null}=p;const[drawer,setDrawer]=useState<any>(initialDrawer);const[season,setSeason]=useState(Math.max(0,p.seasons.findIndex((s:any)=>s.seasonNumber===p.currentSeason)));const[episode,setEpisode]=useState(p.currentEpisodeIndex);const[focus,setFocus]=useState<'top'|'timeline'|'drawer'>('top');
 useEffect(()=>{if(isOpen){setDrawer(initialDrawer);setFocus(initialDrawer?'drawer':'top')}},[isOpen,initialDrawer]);useEffect(()=>setEpisode(p.currentEpisodeIndex),[p.currentEpisodeIndex]);
 const seasonData=p.seasons[season];const eps=seasonData?.episodes?.length?seasonData.episodes:p.episodes;
 useEffect(()=>{if(!isOpen)return;const h=(e:KeyboardEvent)=>{if(e.key==='Escape'||e.key==='Backspace'||e.keyCode===10009){if(drawer){setDrawer(null);setFocus('top')}else p.onClose();return}if(e.key==='ArrowDown'){if(!drawer){setDrawer(p.isMovie?'more':'episodes');setFocus('drawer')}return}if(e.key==='ArrowUp'){if(drawer==='episodes'&&season>0){setSeason(s=>s-1);setEpisode(0);return}if(drawer){setDrawer(null);setFocus('top');return}if(focus==='timeline')setFocus('top');return}if(e.key==='ArrowLeft'){if(focus==='timeline'){p.onSeek?.(Math.max(0,(p.currentTime||0)-10))}else if(drawer==='episodes'&&episode>0)setEpisode(i=>i-1);else if(focus==='top')setFocus('timeline');return}if(e.key==='ArrowRight'){if(focus==='timeline'){p.onSeek?.(Math.min(p.duration||Infinity,(p.currentTime||0)+10))}else if(drawer==='episodes'&&episode<eps.length-1)setEpisode(i=>i+1);else if(focus==='top')setFocus('timeline');return}if(e.key==='Enter'||e.key===' '){e.preventDefault();if(drawer==='episodes'){const ep=eps[episode];if(ep)p.onPlayEpisode(ep.id,0)}else if(drawer==='settings'){p.onSelectType(p.selectedType==='sub'?'dub':'sub')}else if(focus==='timeline')p.onTogglePlay?.();}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[isOpen,drawer,focus,season,episode,eps,p]);
 if(!isOpen)return null;const progress=p.duration?Math.min(100,((p.currentTime||0)/p.duration)*100):0;
 return <div className="pointer-events-none absolute inset-0 z-50 select-none"><div className="absolute inset-0 bg-gradient-to-b from-black/75 via-transparent to-black/85"/>
  <div className="pointer-events-auto absolute inset-x-0 top-0 flex items-start justify-between p-8 lg:p-12"><button onClick={p.onBack} className={`flex items-center gap-3 rounded-[20px] border px-4 py-3 ${focus==='top'?'border-white/60 bg-white/10':'border-white/10 bg-black/35'}`}><ArrowLeft/><div className="text-left"><div className="text-xs font-black text-white/40">BACK</div><div className="max-w-[50vw] truncate font-black">{p.animeTitle}</div><div className="text-xs text-white/45">Episode {p.episodeNumber}{p.episodeTitle?' • '+p.episodeTitle:''}</div></div></button><button onClick={()=>setDrawer('settings')} className="rounded-[18px] border border-white/10 bg-black/35 p-4"><Settings/></button></div>
  <div className="pointer-events-auto absolute inset-x-0 bottom-0 p-8 lg:p-12"><div className={`h-2 rounded-full bg-white/20 ${focus==='timeline'?'h-3 ring-2 ring-white/30':''}`}><div className="h-full rounded-full bg-gradient-to-r from-fuchsia-400 via-violet-400 to-cyan-300" style={{width:progress+'%'}}/></div><div className="mt-3 flex justify-between text-xs font-bold text-white/65"><span>{fmt(p.currentTime||0)}</span><span>{p.duration?'-'+fmt(Math.max(0,p.duration-(p.currentTime||0))):'--:--'}</span></div><div className="mt-5 flex items-center justify-between"><div className="text-[10px] font-black uppercase tracking-[.25em] text-white/35">{p.isPlaying?'Playing':'Paused'} • Left/Right seek</div><button onClick={()=>setDrawer(p.isMovie?'more':'episodes')} className="flex items-center gap-2 rounded-[16px] border border-white/10 bg-black/45 px-4 py-3 text-xs font-black"><ChevronUp className="h-4 w-4"/>{p.isMovie?'More Like This':'Seasons & Episodes'}</button></div></div>
  {drawer==='episodes'&&<div className="pointer-events-auto absolute inset-x-0 bottom-0 h-[58%] border-t border-white/10 bg-[#0b0d13]/98 shadow-2xl"><div className="flex h-full"><aside className="w-[260px] overflow-y-auto border-r border-white/10 p-6"><div className="mb-4 text-[10px] font-black uppercase tracking-[.25em] text-white/35">Seasons</div>{p.seasons.map((s:any,i:number)=><button key={s.seasonNumber||i} onClick={()=>{setSeason(i);setEpisode(0)}} className={`mb-2 w-full rounded-[16px] border p-4 text-left text-sm font-black ${i===season?'bg-white text-black border-white':'bg-white/[.03] border-white/8 text-white/55'}`}>{s.title||'Season '+s.seasonNumber}</button>)}</aside><section className="flex-1 overflow-y-auto p-6"><div className="mb-5 flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.25em] text-white/35">Episodes</div><div className="text-xl font-black">{seasonData?.title||'Season '+(p.currentSeason||1)}</div></div><button onClick={()=>setDrawer(null)}><X/></button></div><div className="grid gap-3 md:grid-cols-2">{eps.map((ep:any,i:number)=><button key={ep.id||i} onClick={()=>p.onPlayEpisode(ep.id,0)} className={`flex items-center gap-3 rounded-[18px] border p-3 text-left ${i===episode?'border-white bg-white/10':'border-white/8 bg-white/[.025]'}`}><img src={ep.image||''} alt="" className="h-16 w-28 rounded-xl object-cover"/><div className="min-w-0"><div className="text-[10px] text-white/35">EPISODE {ep.number}</div><div className="truncate text-sm font-black">{ep.title||'Episode '+ep.number}</div></div></button>)}</div></section></div></div>}
  {drawer==='settings'&&<div className="pointer-events-auto absolute right-0 top-0 bottom-0 w-[420px] border-l border-white/10 bg-[#0b0d13]/98 p-8 shadow-2xl"><div className="mb-8 flex justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.25em] text-white/35">Player</div><div className="text-2xl font-black">Settings</div></div><button onClick={()=>setDrawer(null)}><X/></button></div>{[[AudioLines,'Audio & Subtitles',p.selectedType.toUpperCase()],[MonitorPlay,'Video Quality','Auto'],[Gauge,'Playback Speed','1×'],[Volume2,'Audio Output','TV']].map(([I,l,v]:any)=><button key={l} onClick={()=>l==='Audio & Subtitles'&&p.onSelectType(p.selectedType==='sub'?'dub':'sub')} className="mb-3 flex w-full items-center gap-4 rounded-[18px] border border-white/8 bg-white/[.035] p-5 text-left"><I className="text-violet-300"/><div><div className="font-black">{l}</div><div className="text-xs text-white/35">{v}</div></div></button>)}</div>}
 </div>;
}