import React,{useCallback,useEffect,useMemo,useState}from'react';
import useSWR from'swr';
import{useLocation}from'wouter';
import{Bookmark,Film,Home,LogOut,Search,Settings,Volume2,Monitor,ChevronRight,Sparkles,Compass}from'lucide-react';
import{api}from'../lib/api';
import{AnimeItem}from'../types';
import{historyUtil,HistoryItem}from'../lib/history';
import{libraryManager,LibraryItem}from'../lib/library';
import{useTVMode}from'../lib/TVModeContext';
import{TVSidebar,TVNavSection,TV_NAV_ITEMS}from'../components/tv/TVSidebar';
import{TVHero}from'../components/tv/TVHero';
import{TVContentRow}from'../components/tv/TVContentRow';
import{TVSearchView}from'../components/tv/TVSearchView';
import{TVDetailsView}from'../components/tv/TVDetailsView';
import{groupFranchises}from'../lib/franchise';

export function TVApp(){
 const[location,setLocation]=useLocation();const{setTVMode}=useTVMode();
 const routeId=location.startsWith('/details/')?decodeURIComponent(location.slice(9)):null;
 const{data:routeAnime}=useSWR(routeId?'tv-route-'+routeId:null,()=>api.getDetails(routeId!),{revalidateOnFocus:false});
 const[active,setActive]=useState<TVNavSection>('home');const[selected,setSelected]=useState<AnimeItem|null>(null);
 const[focus,setFocus]=useState<'sidebar'|'hero'|'rows'>('hero');const[side,setSide]=useState(0);const[expanded,setExpanded]=useState(false);const[heroButton,setHeroButton]=useState(0);const[row,setRow]=useState(0);const[card,setCard]=useState(0);
 const[history,setHistory]=useState<HistoryItem[]>(historyUtil.getHistory());const[watchlist,setWatchlist]=useState<LibraryItem[]>(libraryManager.getWatchlist());
 useEffect(()=>{if(routeAnime)setSelected(routeAnime as AnimeItem);else if(!routeId)setSelected(null)},[routeAnime,routeId]);
 const refresh=useCallback(()=>{setHistory(historyUtil.getHistory());setWatchlist(libraryManager.getWatchlist())},[]);
 useEffect(()=>{refresh();const f=()=>refresh();window.addEventListener('kinoma_library_update',f);return()=>window.removeEventListener('kinoma_library_update',f)},[refresh]);
 const{data:tr}=useSWR('tv-new-trending',api.getTrending,{dedupingInterval:120000});const{data:pop}=useSWR('tv-new-popular',api.getPopular,{dedupingInterval:120000});const{data:schedule}=useSWR('tv-new-schedule',api.getAiringToday,{dedupingInterval:120000});
 const trending=useMemo(()=>groupFranchises(tr?.results||[]),[tr]);const popular=useMemo(()=>groupFranchises(pop?.results||[]),[pop]);const newAnime=useMemo(()=>groupFranchises(schedule?.results||[]),[schedule]);
 const heroItems=useMemo(()=>Array.from(new Map([...popular,...trending].filter(x=>(x.type||'').toLowerCase()!=='movie').map(x=>[x.id,x])).values()).slice(0,5),[popular,trending]);
 const[heroIndex,setHeroIndex]=useState(0);useEffect(()=>{if(heroItems.length<2)return;const t=setInterval(()=>setHeroIndex(i=>(i+1)%heroItems.length),5000);return()=>clearInterval(t)},[heroItems]);
 const hero=heroItems[heroIndex]||heroItems[0]||null;
 const listItems=useMemo(()=>watchlist.map(x=>({id:x.id,title:x.title,image:x.image,cover:x.image,genres:[]} as AnimeItem)),[watchlist]);
 const rows=useMemo(()=>{if(active==='home')return[
  history.length?{id:'continue',title:'Continue Watching',subtitle:'Pick up where you left off',historyItems:history,isContinueWatching:true,items:[]}:null,
  trending.length?{id:'trending',title:'Trending Now',subtitle:'Popular on Kinoma',items:trending,historyItems:[],isContinueWatching:false}:null,
  newAnime.length?{id:'new',title:'Airing Today',subtitle:'Fresh episodes',items:newAnime,historyItems:[],isContinueWatching:false}:null,
  popular.length?{id:'popular',title:'Popular Anime',subtitle:'More to explore',items:popular,historyItems:[],isContinueWatching:false}:null
 ].filter(Boolean) as any[];if(active==='mylist')return[{id:'list',title:'My List',subtitle:listItems.length+' saved titles',items:listItems,historyItems:[],isContinueWatching:false}];if(active==='movies')return[{id:'movies',title:'Movies & OVAs',items:popular,historyItems:[],isContinueWatching:false}];if(active==='new_season')return[{id:'anime',title:'Anime',subtitle:'Current releases',items:newAnime.length?newAnime:trending,historyItems:[],isContinueWatching:false}];if(active==='genres')return[{id:'discover',title:'Discover',subtitle:'Start with something new',items:popular,historyItems:[],isContinueWatching:false}];return[]},[active,history,trending,newAnime,popular,listItems]);
 const launch=(id:string,t=0)=>{try{sessionStorage.setItem('kinoma_auto_fullscreen','1')}catch{}setLocation('/watch/'+encodeURIComponent(id)+'?t='+Math.floor(t)+'&fs=1')};
 const selectCard=(ri:number,ci:number)=>{const r=rows[ri];if(!r)return;if(r.isContinueWatching){const h=r.historyItems[ci];if(h)launch(h.episodeId||h.slug,h.playbackTimestamp)}else if(r.items[ci])setSelected(r.items[ci])};
 const chooseNav=(s:TVNavSection)=>{setActive(s);setFocus(s==='home'?'hero':'rows');setSide(TV_NAV_ITEMS.findIndex(x=>x.id===s));setRow(0);setCard(0);setExpanded(false)};
 const key=useCallback((e:KeyboardEvent)=>{if(selected||active==='search')return;if(e.key==='ArrowLeft'){if(focus==='sidebar'){return}if(focus==='hero'){if(heroButton>0)setHeroButton(i=>i-1);else{setFocus('sidebar');setExpanded(true)}}else if(card>0)setCard(i=>i-1);else{setFocus('sidebar');setExpanded(true)}}else if(e.key==='ArrowRight'){if(focus==='sidebar'){setFocus(active==='home'?'hero':'rows');setExpanded(false)}else if(focus==='hero'&&heroButton<2)setHeroButton(i=>i+1);else if(focus==='rows'){const n=rows[row]?.isContinueWatching?rows[row].historyItems.length:rows[row]?.items.length||0;if(card<n-1)setCard(i=>i+1)}}else if(e.key==='ArrowUp'){if(focus==='sidebar'){if(side>0)setSide(i=>i-1)}else if(focus==='rows'){if(row>0){setRow(i=>i-1);setCard(0)}else if(active==='home'){setFocus('hero');setHeroButton(0)}}else if(focus==='hero'){setFocus('sidebar');setExpanded(true)}}else if(e.key==='ArrowDown'){if(focus==='sidebar'){if(side<TV_NAV_ITEMS.length)setSide(i=>i+1)}else if(focus==='hero'&&rows.length){setFocus('rows');setRow(0);setCard(0)}else if(focus==='rows'&&row<rows.length-1){setRow(i=>i+1);setCard(0)}}else if(e.key==='Enter'||e.key===' '){e.preventDefault();if(focus==='sidebar'){if(side===TV_NAV_ITEMS.length){setTVMode(false);setLocation('/')}else if(TV_NAV_ITEMS[side])chooseNav(TV_NAV_ITEMS[side].id)}else if(focus==='hero'&&hero){if(heroButton===0)launch(hero.id);else if(heroButton===1){libraryManager.toggleWatchlist({id:hero.id,title:typeof hero.title==='string'?hero.title:hero.title?.english||hero.title?.romaji||'',image:hero.image});refresh()}else setSelected(hero)}else if(focus==='rows')selectCard(row,card)}else if(e.key==='Escape'||e.key==='Backspace'){if(focus!=='sidebar'){setFocus('sidebar');setExpanded(true)}else{setTVMode(false);setLocation('/')}}},[selected,active,focus,heroButton,card,row,side,rows,hero,refresh,setTVMode,setLocation]);
 useEffect(()=>{window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[key]);
 if(selected)return <TVDetailsView animeId={selected.id} initialItem={selected} onPlayEpisode={(id,t)=>launch(id,t)} onBack={()=>{setSelected(null);setLocation('/tv')}}/>;
 if(active==='search')return <div className="min-h-screen bg-[#080a10]"><TVSidebar activeSection={active} onSelectSection={chooseNav} isFocused={focus==='sidebar'} focusedIndex={side} isExpanded={expanded} setIsExpanded={setExpanded} onExitTVMode={()=>{setTVMode(false);setLocation('/')}}/><div className="pl-[92px]"><TVSearchView onSelectAnime={a=>setSelected(a)} onBackToSidebar={()=>chooseNav('home')}/></div></div>;
 if(active==='settings')return <div className="min-h-screen bg-[#080a10] text-white"><TVSidebar activeSection={active} onSelectSection={chooseNav} isFocused={focus==='sidebar'} focusedIndex={side} isExpanded={expanded} setIsExpanded={setExpanded} onExitTVMode={()=>{setTVMode(false);setLocation('/')}}/><div className="pl-[92px] px-10 py-14 lg:px-16"><div className="max-w-3xl"><div className="text-[10px] font-black uppercase tracking-[.25em] text-white/35">Kinoma TV</div><h1 className="mt-2 text-5xl font-black">Settings</h1><div className="mt-8 space-y-3"><div className="flex items-center gap-4 rounded-[24px] border border-white/8 bg-white/[.035] p-5"><Volume2 className="text-violet-300"/><div><div className="font-black">Audio & Subtitles</div><div className="text-xs text-white/35">Choose your preferred track inside the player.</div></div></div><div className="flex items-center gap-4 rounded-[24px] border border-white/8 bg-white/[.035] p-5"><Monitor className="text-cyan-300"/><div><div className="font-black">TV playback</div><div className="text-xs text-white/35">Remote-first fullscreen playback is enabled.</div></div></div></div></div></div></div>;
 return <div className="min-h-screen overflow-x-hidden bg-[#080a10] text-white"><TVSidebar activeSection={active} onSelectSection={chooseNav} isFocused={focus==='sidebar'} focusedIndex={side} isExpanded={expanded} setIsExpanded={setExpanded} onExitTVMode={()=>{setTVMode(false);setLocation('/')}}/><main className="pl-[92px]"><TVHero item={hero} isFocused={focus==='hero'} focusedButtonIndex={heroButton} onPlay={i=>launch(i.id)} onMoreInfo={i=>setSelected(i)} onToggleList={refresh}/><div className="pb-20 pt-4">{rows.map((r:any,i:number)=><TVContentRow key={r.id} {...r} isRowFocused={focus==='rows'&&row===i} focusedCardIndex={card} rowIndex={i} onSelectCard={ci=>selectCard(i,ci)}/>)}</div></main></div>;
}